# registry/ticker_config.py

TICKER_LABELS = {
    "NVDA":    {"label": "NVIDIA",     "full": "NVIDIA Corp.",          "weight": 749},
    "AAPL":    {"label": "AAPL",       "full": "Apple Inc.",            "weight": 659},
    "MSFT":    {"label": "MSFT",       "full": "Microsoft Corp.",       "weight": 527},
    "AMZN":    {"label": "AMZN",       "full": "Amazon.com Inc.",       "weight": 359},
    "GOOG":    {"label": "GOOGL",      "full": "Alphabet Inc.",         "weight": 441},
    "AVGO":    {"label": "AVGO",       "full": "Broadcom Inc.",         "weight": 270},
    "META":    {"label": "META",       "full": "Meta Platforms",        "weight": 243},
    "TSLA":    {"label": "TSLA",       "full": "Tesla Inc.",            "weight": 193},
    "BRK-B":   {"label": "BRK.B",      "full": "Berkshire Hathaway B",  "weight": 159},
    "EUR=X":   {"label": "EUR/USD",    "full": "Euro / US Dollar",      "weight": 576},
    "JPY=X":   {"label": "USD/JPY",    "full": "US Dollar / Yen",       "weight": 136},
    "GBP=X":   {"label": "GBP/USD",    "full": "British Pound / USD",   "weight": 119},
    "CAD=X":   {"label": "USD/CAD",    "full": "US Dollar / CAD",       "weight": 91},
    "CHF=X":   {"label": "USD/CHF",    "full": "US Dollar / CHF",       "weight": 36},
    "BTC-USD": {"label": "BTC",        "full": "Bitcoin",               "weight": 540},
    "ETH-USD": {"label": "ETH",        "full": "Ethereum",              "weight": 170},
    "BNB-USD": {"label": "BNB",        "full": "BNB Chain",             "weight": 44},
    "XRP-USD": {"label": "XRP",        "full": "Ripple",                "weight": 42},
    "SOL-USD": {"label": "SOL",        "full": "Solana",                "weight": 24},
    "BZ=F":    {"label": "Brent",      "full": "Brent Crude Oil",       "weight": 184},
    "CL=F":    {"label": "WTI",        "full": "WTI Crude Oil",         "weight": 178},
    "GC=F":    {"label": "Gold",       "full": "Gold",                  "weight": 72},
    "HG=F":    {"label": "Copper",     "full": "Copper",                "weight": 55},
    "NG=F":    {"label": "Nat Gas",    "full": "Natural Gas",           "weight": 36},
    "ZC=F":    {"label": "Corn",       "full": "Corn",                  "weight": 31},
    "ZS=F":    {"label": "Soybeans",   "full": "Soybeans",              "weight": 24},
    "SI=F":    {"label": "Silver",     "full": "Silver",                "weight": 19},
    "KE=F":    {"label": "Wheat",      "full": "Wheat (KC HRW)",        "weight": 18},
    "KC=F":    {"label": "Coffee",     "full": "Coffee",                "weight": 15},
    "TLT":     {"label": "US 20Y+",    "full": "iShares 20+ Year Tsy",  "weight": 350},
    "IEF":     {"label": "US 7-10Y",   "full": "iShares 7-10Y Tsy",     "weight": 250},
    "SHY":     {"label": "US 1-3Y",    "full": "iShares 1-3Y Tsy",      "weight": 150},
    "MBB":     {"label": "MBS",        "full": "iShares MBS ETF",       "weight": 100},
    "EMB":     {"label": "EM Bonds",   "full": "iShares EM Bond ETF",   "weight": 90},
    "SDEU.L":  {"label": "Bund",       "full": "German Bund ETF",       "weight": 60},
    "1482.T":  {"label": "JGB",        "full": "Japan Govt Bond ETF",   "weight": 40},
    "IGLT.L":  {"label": "Gilts",      "full": "iShares UK Gilts ETF",  "weight": 20},
}

